Add files via upload
GN-zll/java_hw pull request #1
Opened 2023-09-15 08:32 UTC by GN-zll

Сделал ручками на гитхабе, чтобы просто сдать дз уже, надеюсь что в следующем дз у меня получиться сделать все как у адекватного человека через IDE

2023-09-15 09:11 UTC, ASemenovng requested changes

2023-09-15 09:11 UTC, ASemenovng commented on Homework1.java
> +    static int normalize(int angle) {
что будет при вызове normalize(-1)?

2023-09-15 09:14 UTC, ASemenovng commented on Homework1.java
> +    static int max(int x, int y, int z) {
можно так, а можно Math.max()
это можно не исправлять, но в целом лучше пользоваться теми классами и методами, которые уже есть в стандартной библиотеке, а не делать свое каждый раз

2023-09-15 09:14 UTC, ASemenovng commented on Homework1.java
> +    static int fact(int n) {
если ты передаешь 0 в функцию, то получишь ошибку. Лучше это предусмотреть

2023-09-15 09:14 UTC, ASemenovng commented on Homework1.java
> +    static BigInteger fact(BigInteger n) {
аналогично

2023-09-15 09:23 UTC, ASemenovng requested changes

2023-09-15 09:23 UTC, ASemenovng commented on Homework1.java
> +    static int average(int... nums) {
1. замени возвращаемое значение на double
2. попробуй вызвать average() без аргументов и посмотри, что будет

2023-09-15 09:23 UTC, ASemenovng commented on Homework1.java
> +        int sum_max = 0;
1. никто не запрещал отрицательные элементы, так что такой вариант поиска min/max не подойдет
2. 100000000 - int может быть больше, так что тут аналогично 
Так что тут лучше пользоваться Integer.MAX_VALUE и Integer.MIN_VALUE, либо просто положить в min/max первый элемент и сравнивать с ним

2023-09-15 09:23 UTC, ASemenovng commented on Homework1.java
> +        sum = square[0][0] + square[1][1] + square[2][2] + square[3][3];
А если размер квадрата не 4х4, а другой?)

2023-09-15 09:23 UTC, ASemenovng commented on Homework1.java
> +        for (int i = 0; i < arr1.length; ++i) {
Если ты хочешь скопировать массив, то есть Arrays.copyOf()
Но тут в целом это можно сделать без дополнительного массива

2023-09-15 09:23 UTC, ASemenovng commented on Homework1.java
> +        int a = 0;
ок, только лучше не называть переменные по типу a - непонятно, что это значит. Назови или i, j, k - это привычная переменная для итераций, или назови какой нибудь index, что нибудь такое

2023-09-16 17:53 UTC, ASemenovng requested changes

2023-09-16 17:53 UTC, ASemenovng commented on Homework1.java
> +        BigInteger factorial = BigInteger.valueOf(1);
1. Есть константы BigInteger.ONE, так что не нужно заводить лишние переменные
2. Вот это для чего ты делаешь?)
```java
long m = n.longValue();
```
Смысл ведь в том, что предполагается, что тебе приходит большое число, которое не влазит в стандартные типы данных

2023-11-16 09:57 UTC, GN-zll commented on Homework1.java
> +    static int fact(int n) {
Исправил

2023-11-16 10:05 UTC, GN-zll commented on Homework1.java
> +    static BigInteger fact(BigInteger n) {
Исправил, и вообще нормально переписал это

2023-11-16 10:10 UTC, GN-zll commented on Homework1.java
> +    static int average(int... nums) {
Исправил

2023-11-16 10:12 UTC, GN-zll commented on Homework1.java
> +    static int normalize(int angle) {
Исправил

2023-11-16 10:31 UTC, GN-zll commented on Homework1.java
> +        int sum_max = 0;
Исправил

2023-11-16 10:33 UTC, GN-zll commented on Homework1.java
> +        sum = square[0][0] + square[1][1] + square[2][2] + square[3][3];
Переписал, почему-то у меня в голове магические квадраты именно 4 на 4

2023-11-16 10:33 UTC, GN-zll commented on Homework1.java
> +        BigInteger factorial = BigInteger.valueOf(1);
Да я с компараторами тогда не разобрался, переписал нормально сейчас

2023-12-01 16:02 UTC, merged