Hw2
GN-zll/java_hw pull request #2
Opened 2023-09-25 12:04 UTC by GN-zll

homework2

2023-10-16 14:40 UTC, KozlovAV426 requested changes

2023-10-16 14:40 UTC, KozlovAV426 commented on .idea/.gitignore
папку .idea не загружать в git

2023-10-16 14:40 UTC, KozlovAV426 commented on out/production/java_hw/.gitignore
> +# Compiled class file
папку out  тоже убрать

2023-10-16 14:40 UTC, KozlovAV426 commented on Homework2/intHolder.java
> +    int x;
private int x

2023-10-16 14:40 UTC, KozlovAV426 commented on Homework2/intHolder.java
> +        x = new_x;
для переменных используется camelCase, newX

2023-10-16 14:40 UTC, KozlovAV426 commented on Homework2/intHolder.java
> +    public static intHolder sum(intHolder a, intHolder b) {
методы sum, sub и остальные должны прибавлять к текущему значению

2023-10-16 14:40 UTC, KozlovAV426 commented on Homework2/intHolder.java
> +    public void is(int new_x) {
что делает этот метод?

2023-10-16 14:40 UTC, KozlovAV426 commented on Homework2/Point.java
> +    public Point translate(double new_x, double new_y) {
camelCase newX

2023-10-16 14:40 UTC, KozlovAV426 commented on Homework2/Parrot.java
> +    private boolean documents;
для булевских переменных можно использовать приставки is, has и тд

2023-10-16 14:40 UTC, KozlovAV426 commented on Homework2/Dog.java
> +        Expensive,
переменные в енаме в UPPER_CASE

2023-11-13 00:17 UTC, GN-zll commented on Homework2/intHolder.java
> +    int x;
Испрвил

2023-11-13 00:17 UTC, GN-zll commented on Homework2/intHolder.java
> +    public static intHolder sum(intHolder a, intHolder b) {
Испрвил

2023-11-13 00:18 UTC, GN-zll commented on Homework2/Point.java
> +    public Point translate(double new_x, double new_y) {
Испрвил

2023-11-13 00:18 UTC, GN-zll commented on Homework2/Dog.java
> +        Expensive,
Испрвил

2023-12-01 16:59 UTC, merged